# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
absl-py=2.1.0=pypi_0
art=6.4=pypi_0
axial-positional-embedding=0.2.1=pypi_0
bzip2=1.0.8=h0ad9c76_8
ca-certificates=2025.11.12=h4c7d964_0
certifi=2022.12.7=pypi_0
charset-normalizer=2.1.1=pypi_0
cloudpickle=3.1.1=pypi_0
colorama=0.4.6=pypi_0
colt5-attention=0.11.1=pypi_0
contourpy=1.3.1=pypi_0
cycler=0.12.1=pypi_0
einops=0.8.0=pypi_0
filelock=3.13.1=pypi_0
fonttools=4.55.3=pypi_0
grpcio=1.68.1=pypi_0
idna=3.4=pypi_0
imageio=2.36.1=pypi_0
jenkspy=0.4.1=pypi_0
jinja2=3.1.3=pypi_0
joblib=1.4.2=pypi_0
kiwisolver=1.4.7=pypi_0
lazy-loader=0.4=pypi_0
libffi=3.5.2=h52bdfb6_0
liblzma=5.8.1=h2466b09_2
libsqlite=3.51.1=hf5d6505_1
libzlib=1.3.1=h2466b09_2
lime=0.2.0.1=pypi_0
llvmlite=0.44.0=pypi_0
lmdb=1.6.2=pypi_0
local-attention=1.9.15=pypi_0
markdown=3.7=pypi_0
markupsafe=2.1.5=pypi_0
matplotlib=3.10.0=pypi_0
mpmath=1.3.0=pypi_0
networkx=3.2.1=pypi_0
numba=0.61.0=pypi_0
numpy=1.26.3=pypi_0
openssl=3.6.0=h725018a_0
packaging=24.2=pypi_0
pandas=2.2.3=pypi_0
pillow=10.2.0=pypi_0
pip=25.3=pyh8b19718_0
portalocker=3.1.1=pypi_0
product-key-memory=0.2.11=pypi_0
protobuf=5.29.2=pypi_0
pyarrow=19.0.1=pypi_0
pyparsing=3.2.0=pypi_0
python=3.10.16=h37870fc_1_cpython
python-dateutil=2.9.0.post0=pypi_0
pytz=2024.2=pypi_0
pywin32=308=pypi_0
reformer-pytorch=1.4.4=pypi_0
requests=2.28.1=pypi_0
scikit-base=0.12.0=pypi_0
scikit-image=0.25.0=pypi_0
scikit-learn=1.5.2=pypi_0
scipy=1.14.1=pypi_0
setuptools=80.9.0=pyhff2d567_0
shap=0.46.0=pypi_0
six=1.17.0=pypi_0
sktime=0.35.0=pypi_0
slicer=0.0.8=pypi_0
sympy=1.13.1=pypi_0
tabulate=0.9.0=pypi_0
tensorboard=2.18.0=pypi_0
tensorboard-data-server=0.7.2=pypi_0
threadpoolctl=3.5.0=pypi_0
tifffile=2024.12.12=pypi_0
tk=8.6.13=h2c6b04d_3
torch=2.0.1+cu118=pypi_0
torchaudio=2.0.2+cu118=pypi_0
torchdata=0.6.1=pypi_0
torchtext=0.15.2=pypi_0
torchvision=0.15.2+cu118=pypi_0
tqdm=4.67.1=pypi_0
triton=2.1.0=pypi_0
typing-extensions=4.9.0=pypi_0
tzdata=2024.2=pypi_0
ucrt=10.0.26100.0=h57928b3_0
urllib3=1.26.13=pypi_0
vc=14.3=h2b53caa_33
vc14_runtime=14.44.35208=h818238b_33
vcomp14=14.44.35208=h818238b_33
werkzeug=3.1.3=pypi_0
wheel=0.45.1=pyhd8ed1ab_1
wrapt=1.17.0=pypi_0
zipp=3.21.0=pypi_0
